services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./apache-vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db
    links:
      - db
    networks:
      - app-network
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: hospital_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/hospital_db.sql:/docker-entrypoint-initdb.d/hospital_db.sql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - app-network

  # Jitsi Video Calling Services
  prosody:
    image: jitsi/prosody:stable
    restart: always
    networks:
      - app-network
    env_file:
      - .env

  jicofo:
    image: jitsi/jicofo:stable
    restart: always
    depends_on:
      - prosody
    networks:
      - app-network
    env_file:
      - .env

  jvb:
    image: jitsi/jvb:stable
    restart: always
    depends_on:
      - prosody
    ports:
      - "10000:10000/udp"
    networks:
      - app-network
    env_file:
      - .env

  jitsi:
    image: jitsi/web:stable
    restart: always
    depends_on:
      - prosody
      - jicofo
    ports:
      - "8443:443"
    networks:
      - app-network
    env_file:
      - .env

volumes:
  db_data:


networks:
  app-network:
    driver: bridge
