services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./apache-vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db
    links:
      - db
    networks:
      - app-network
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: hospital_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/hospital_db.sql:/docker-entrypoint-initdb.d/hospital_db.sql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
